# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "deploy" workflow 
   deploy:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # needs: [build] # Only run this workflow when "build" workflow succeeds
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
      steps:
      - uses: actions/checkout@master

      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master
      
      - name: Log into ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.LOGIN_SERVER }} #mycontainer.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker build
        run: |
          docker build . -t ${{ secrets.LOGIN_SERVER }}/techchallengeapp:${{ github.sha }}
          docker push ${{ secrets.LOGIN_SERVER }}/techchallengeapp:${{ github.sha }}